blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/bright-room/repo-policies/discussions
    about: For questions and general discussion, please use Discussions.
